### ISSUE TITLE
Import IGC freeze

### ISSUE THREAD

**Issue by Sqefs** [laggery/Flightbook-MobileApp#25]
Hi,

It's me again... 

We were testing the import IGC file again with some of my girlfriend IGC files and we come across another issue.

![image](https://user-images.githubusercontent.com/94315642/144760062-fca9f4fe-f407-4487-8e0e-1f20ffcec21b.png)

It stays like that on her laptop.

When we try the same file thought her mobile phone (Android) it succeed.

![Screenshot_20211205-200403_Flightbook](https://user-images.githubusercontent.com/94315642/144760091-4441a886-269a-4405-b83f-bea35f7925fd.jpg)

She managed to upload the same tracks a month ago without trouble.

She use a reversale variometer through logfly 5.110.
We try on my computer and with chrome/edge/firefox and we still have the same result.

here is a test file :
[test2.zip](https://github.com/laggery/Flightbook-MobileApp/files/7656629/test2.zip)

Is there a difference between the Android App and the website ?

Thanks

David

**Comment by laggery** [comment]
Hi David

Thanks for reporting this issue.

Yes, the web browser version was 2.2.3 and the last Android version was 2.2.2. The new feature I implemented last month had a side effect. I could fix it this morning. You can test it with the web browser under https://m.flightbook.ch 
I published the new version in the app store this morning and it should be available for download in a few hours.

Let me know if everything works so that I can close the bug.

Regards
Yannick

**Comment by Sqefs** [comment]
Wow, lightning fast correction !

My girlfriend test it again this afternoon and it works flawlessly!

Thanks
